### ISSUE TITLE
[Suggestion] Documentation Update

### ISSUE THREAD

**Issue by boxbeatsy** [jonstacks/aws#20]
Thanks for the useful tool!  Just a suggestion: in the documentation around fetching RDS log download URL's, it may be helpful to identify that "fc16fu3t5aah9e9" should be your RDS DB identifier name.

Also, the script below is what I'm using to download all RDS logs.

#!/bin/bash
for filename in $( aws rds describe-db-log-files --output json --db-instance-identifier YOUR_DB_IDENTIFIER_NAME | jq -r '.DescribeDBLogFiles[] | .LogFileName' )
do
    echo $filename
    LOG_URL=$(/home/aaron/go/bin/rds-logs-download-url YOUR_DB_IDENTIFIER_NAME $filename)
    echo $LOG_URL
    curl -sf -o ./error/$(basename $filename) $LOG_URL
done

**Comment by jonstacks** [comment]
@boxbeatsy, thanks for the suggestion. I'll work on updating the documentation for this.

**Comment by jonstacks** [comment]
Fix to the documentation is made in #23. Based on this suggestion and the request in #21, a new command `sync-rds-logs` has been created which should help reduce some of the common bash boilerplate for syncing the full RDS logs from AWS to a local directory.
