### ISSUE TITLE
rds-logs-download-url - Incremental mode?

### ISSUE THREAD

**Issue by julianodba** [jonstacks/aws#21]
rds-logs-download-url is running in a cron job, but each time it runs all logs are downloaded again. 
So, is there any way to use an incremental mode just like on pgbadger, please?

Apologize if this option already exists but, I couldn't find it in the readme file or help.

Any alternative suggestions are welcome.
Below is the part of the bash script I'm using on cronjob to download any new log change:

```
for filename in $( aws rds describe-db-log-files --db-instance-identifier $rds_id | jq -r '.DescribeDBLogFiles[] | .LogFileName' | sed '/.gz/d' )
do

LOG_NAME=$filename
LOG_URL=$(/root/go/bin/rds-logs-download-url $rds_id $LOG_NAME)
# -s for silent, -f for fail so we can retry on failure
curl -f -o $pg_logs/$(basename $LOG_NAME) $LOG_URL
done;
```

**Comment by jonstacks** [comment]
@julianodba,

I ended up doing the same thing for pgbadger. There isn't an incremental option for this in the CLI, but here is what I had for our pgbadger download script in our `docker-entrypoint.sh` script and the environment variables that are specific to our install that we injected at runtime.

```
POSTGRES_LOGS_DIR="/postgres-logs"
RDS_IDENTIFIER="YOUR_RDS_IDENTIFIER_HERE"
```

```bash
#!/usr/bin/env bash

set -e

case "$1" in
  sync-rds-logs)
    # Sync the logs
    IFS=$'\n'
    for line in $(aws rds describe-db-log-files --db-instance-identifier $RDS_IDENTIFIER)
    do
      filename=$(echo $line | awk '{printf $3}')
      size=$(echo $line | awk '{printf $4}')
      relpath=$(basename $filename)
      localpath="${POSTGRES_LOGS_DIR}/${relpath}"

      if [ -e "$localpath" ]; then
        # Now check if remote size is bigger
        local_size=$(wc -c < $localpath)
        echo "$filename (Local Size: $local_size, Remote Size: $size)"
        if [ "$size" -gt "$local_size" ]; then
          printf "Downloading $filename to '$localpath' --> "
          logURL=$(rds-logs-download-url $RDS_IDENTIFIER $filename)
          curl -sf -o $localpath $logURL
          echo "$(wc -c < $localpath) bytes written."
        fi
      else
        echo "Downloading $filename ..."
        logURL=$(rds-logs-download-url $RDS_IDENTIFIER $filename)
        curl -sf -o $localpath $logURL
      fi
    done

    echo "Deleting files older than 1 week..."
    find /postgres-logs -mtime +7 -type f -delete
    ;;

  pgbadger)
    if [ ! -e "/var/www/html/index.html" ]; then
      echo "<html><body><h1>pgbadger is currently downloading and analyzing log files.</h1><p>please be patient and check back later.</p></body></html>" > /var/www/html/index.html
    fi
    exec pgbadger -j 4 -R 12 -O /var/www/html --prefix '%t:%r:%u@%d:[%p]:' -I /postgres-logs/postgresql.log.*
    ;;

  *)
    exec "$@"
   ;;
esac
```

**Comment by jonstacks** [comment]
@julianodba, I created a dedicated command which roughly re-creates the logic above in a `sync-rds-logs` command. If you want to checkout that branch and try it, feel free to put some feedback on the PR.

**Comment by julianodba** [comment]
**Awesome!**

-- Sorry about the long delay to reply

It seems working fine, but not sure if I'm using it correctly 😅 
Here is my code:
`bucket_prefix=staging
bucket_name=pgbadger
rds_id=mydb
region=ap-southeast-1

rds_pg_logs=/s3/rds_pg_logs/$bucket_prefix/$rds_id/

for filename in $( aws rds describe-db-log-files --db-instance-identifier $rds_id | jq -r '.DescribeDBLogFiles[] | .LogFileName' | sed '/.gz/d' )
do
AWS_DEFAULT_REGION=$region
LOG_URL=$(/root/go/bin/sync-rds-logs $rds_id $rds_pg_logs)
done;` 

Apparently, is running for every existent log file:
`
INFO[0000] Found 5 log files for DBInstanceIdentifier=mydb
INFO[0000] error/postgresql.log.2021-08-07.gz (Local Size: 26314509, Remote Size: 26314509) 
INFO[0000] Not downloading error/postgresql.log.2021-08-07.gz as filesize matches remote 
INFO[0000] error/postgresql.log.2021-08-08 (Local Size: 723230050, Remote Size: 723230050) 
INFO[0000] Not downloading error/postgresql.log.2021-08-08 as filesize matches remote 
INFO[0000] error/postgresql.log.2021-08-09 (Local Size: 730204020, Remote Size: 730204020) 
INFO[0000] Not downloading error/postgresql.log.2021-08-09 as filesize matches remote 
INFO[0000] error/postgresql.log.2021-08-10 (Local Size: 731644145, Remote Size: 731644145) 
INFO[0000] Not downloading error/postgresql.log.2021-08-10 as filesize matches remote 
INFO[0000] error/postgresql.log.2021-08-11 (Local Size: 174884991, Remote Size: 175264511) 
INFO[0000] Downloading error/postgresql.log.2021-08-11 to '/s3/rds_pg_logs/staging/mydb/postgresql.log.2021-08-11' 
INFO[0003] Successfully downloaded error/postgresql.log.2021-08-11 
INFO[0000] Found 5 log files for DBInstanceIdentifier=mydb
INFO[0000] error/postgresql.log.2021-08-07.gz (Local Size: 26314509, Remote Size: 26314509) 
INFO[0000] Not downloading error/postgresql.log.2021-08-07.gz as filesize matches remote 
INFO[0000] error/postgresql.log.2021-08-08 (Local Size: 723230050, Remote Size: 723230050) 
INFO[0000] Not downloading error/postgresql.log.2021-08-08 as filesize matches remote 
INFO[0000] error/postgresql.log.2021-08-09 (Local Size: 730204020, Remote Size: 730204020) 
INFO[0000] Not downloading error/postgresql.log.2021-08-09 as filesize matches remote 
INFO[0000] error/postgresql.log.2021-08-10 (Local Size: 731644145, Remote Size: 731644145) 
INFO[0000] Not downloading error/postgresql.log.2021-08-10 as filesize matches remote 
INFO[0000] error/postgresql.log.2021-08-11 (Local Size: 175284017, Remote Size: 175287539) 
INFO[0000] Downloading error/postgresql.log.2021-08-11 to '/s3/rds_pg_logs/staging/mydb/postgresql.log.2021-08-11' 
INFO[0002] Successfully downloaded error/postgresql.log.2021-08-11 
INFO[0000] Found 5 log files for DBInstanceIdentifier=mydb
INFO[0000] error/postgresql.log.2021-08-07.gz (Local Size: 26314509, Remote Size: 26314509) 
INFO[0000] Not downloading error/postgresql.log.2021-08-07.gz as filesize matches remote 
INFO[0000] error/postgresql.log.2021-08-08 (Local Size: 723230050, Remote Size: 723230050) 
INFO[0000] Not downloading error/postgresql.log.2021-08-08 as filesize matches remote 
INFO[0000] error/postgresql.log.2021-08-09 (Local Size: 730204020, Remote Size: 730204020) 
INFO[0000] Not downloading error/postgresql.log.2021-08-09 as filesize matches remote 
INFO[0000] error/postgresql.log.2021-08-10 (Local Size: 731644145, Remote Size: 731644145) 
INFO[0000] Not downloading error/postgresql.log.2021-08-10 as filesize matches remote 
INFO[0000] error/postgresql.log.2021-08-11 (Local Size: 175309929, Remote Size: 175313449) 
INFO[0000] Downloading error/postgresql.log.2021-08-11 to '/s3/rds_pg_logs/staging/mydb/postgresql.log.2021-08-11' 
INFO[0002] Successfully downloaded error/postgresql.log.2021-08-11 
INFO[0000] Found 5 log files for DBInstanceIdentifier=mydb
INFO[0000] error/postgresql.log.2021-08-07.gz (Local Size: 26314509, Remote Size: 26314509) 
INFO[0000] Not downloading error/postgresql.log.2021-08-07.gz as filesize matches remote 
INFO[0000] error/postgresql.log.2021-08-08 (Local Size: 723230050, Remote Size: 723230050) 
INFO[0000] Not downloading error/postgresql.log.2021-08-08 as filesize matches remote 
INFO[0000] error/postgresql.log.2021-08-09 (Local Size: 730204020, Remote Size: 730204020) 
INFO[0000] Not downloading error/postgresql.log.2021-08-09 as filesize matches remote 
INFO[0000] error/postgresql.log.2021-08-10 (Local Size: 731644145, Remote Size: 731644145) 
INFO[0000] Not downloading error/postgresql.log.2021-08-10 as filesize matches remote 
INFO[0000] error/postgresql.log.2021-08-11 (Local Size: 175332181, Remote Size: 175334167) 
INFO[0000] Downloading error/postgresql.log.2021-08-11 to '/s3/rds_pg_logs/staging/mydb/postgresql.log.2021-08-11' 
INFO[0002] Successfully downloaded error/postgresql.log.2021-08-11 
`

**Comment by jonstacks** [comment]
@julianodba,

I might need to update the [sync-rds-logs docs](https://github.com/jonstacks/aws#sync-rds-logs-to-a-local-directory) to have a better description of how the command works. You just need to supply the DB instance identifier and the directory you want to use to sync the logs to. In your above example, you can just do:

```bash
bucket_prefix=staging
bucket_name=pgbadger
rds_id=mydb
region=ap-southeast-1

rds_pg_logs=/s3/rds_pg_logs/$bucket_prefix/$rds_id/
/root/go/bin/sync-rds-logs "$rds_id" "rds_pg_logs"
```

The `sync-rds-logs` command will get a list of all the logs files and compare the size AWS advertises against the size you currently have on disk and only download the ones needed. So you can just run that on a cron and don't have to worry about getting download urls for logs or anything or iterating over them or diffing file sizes. Its all taken care of now!

**Comment by julianodba** [comment]
Thank you so much @jonstacks appreciate that!
